#!/usr/bin/env bash
# common.sh — shared runtime config + helpers for all nemofleet scripts.
#
# Source it via the standard 3-line header (resolves repo root by the
# .nemofleet-root marker, so scripts work from any subfolder and on any host):
#
#   __src="${BASH_SOURCE[0]:-$0}"; __dir="$(cd "$(dirname "$(readlink -f "$__src" 2>/dev/null || echo "$__src")")" && pwd)"
#   while [ "$__dir" != / ] && [ ! -e "$__dir/.nemofleet-root" ]; do __dir="$(dirname "$__dir")"; done
#   NEMOFLEET_ROOT="$__dir"; DIR="$NEMOFLEET_ROOT"; . "$NEMOFLEET_ROOT/lib/common.sh"
#
# Everything host-specific (paths, node bin, ports, container names) is centralised
# here and overridable via $NEMOFLEET_ROOT/.env — see .env.example.

# ── repo root (authoritative: derive from this file's own location) ───────────
NEMOFLEET_ROOT="${NEMOFLEET_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
DIR="$NEMOFLEET_ROOT"   # back-compat alias used throughout the scripts

# ── load local overrides (untracked) ─────────────────────────────────────────
[ -f "$NEMOFLEET_ROOT/.env" ] && . "$NEMOFLEET_ROOT/.env"

# ensure HOME is set (autostart / systemd / cron contexts may not export it)
[ -n "${HOME:-}" ] || HOME="$(getent passwd "$(id -u)" 2>/dev/null | cut -d: -f6)"
export HOME

# ── node / CLI on PATH (nemoclaw + openshell live in node's bin) ──────────────
# Resolve NEMOFLEET_NODE_BIN (explicit .env value, else newest nvm node) and put
# it on PATH. Exported so scripts that set an explicit PATH (e.g. cron) can still
# reference $NEMOFLEET_NODE_BIN instead of a hardcoded version.
if [ -z "${NEMOFLEET_NODE_BIN:-}" ] && [ -d "$HOME/.nvm/versions/node" ]; then
  NEMOFLEET_NODE_BIN="$(ls -d "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -1)"
fi
export NEMOFLEET_NODE_BIN
if [ -n "${NEMOFLEET_NODE_BIN:-}" ]; then
  case ":$PATH:" in *":$NEMOFLEET_NODE_BIN:"*) ;; *) PATH="$NEMOFLEET_NODE_BIN:$PATH";; esac
fi
export PATH

# ── canonical directories (was scattered $DIR/bridge, $DIR/mail-demo, $DIR/bus) ─
LIB_DIR="$NEMOFLEET_ROOT/lib"
SCRIPTS_DIR="$NEMOFLEET_ROOT/scripts"
DEMO_DIR="$NEMOFLEET_ROOT/demo"
TESTS_DIR="$NEMOFLEET_ROOT/tests"
SERVICES_DIR="$NEMOFLEET_ROOT/services"
BRIDGE_DIR="$NEMOFLEET_ROOT/services/bridge"     # was $DIR/bridge
MAIL_DIR="$NEMOFLEET_ROOT/services/mail"          # was $DIR/mail-demo
CONFIG_DIR="$NEMOFLEET_ROOT/config"
SKILLS_DIR="$NEMOFLEET_ROOT/skills"
EVAL_DIR="$NEMOFLEET_ROOT/eval"
DATA_DIR="$NEMOFLEET_ROOT/data"
BUS_DIR="$NEMOFLEET_ROOT/data/bus"                # was $DIR/bus
LOG_DIR="$NEMOFLEET_ROOT/data/logs"
# Secrets are co-located with the bridge service but git-ignored (regenerated by
# scripts/gen-dash-ca.sh, scripts/gen-dash-tls.sh, scripts/rotate-bridge-token.sh).
BRIDGE_TOKEN_FILE="$BRIDGE_DIR/.bridge-token"
NVD_API_KEY_FILE="$BRIDGE_DIR/.nvd-api-key"
mkdir -p "$BUS_DIR/inbox" "$BUS_DIR/outbox" "$LOG_DIR" 2>/dev/null || true

# ── ports / endpoints (override in .env) ─────────────────────────────────────
HERMES_API_PORT="${HERMES_API_PORT:-8642}"
DASH_PORT="${DASH_PORT:-8899}"
BRIDGE_PORT="${BRIDGE_PORT:-9099}"
GATEWAY_PORT="${NEMOCLAW_GATEWAY_PORT:-18080}"
OPENCLAW_UI_PORT="${OPENCLAW_UI_PORT:-18789}"
OPENCLAW2_UI_PORT="${OPENCLAW2_UI_PORT:-18790}"
HERMES_API="http://127.0.0.1:${HERMES_API_PORT}/v1"

# ── sandbox container name fragments (override in .env) ───────────────────────
HERMES_CT_NAME="${HERMES_CT_NAME:-hermes-demo}"
OPENCLAW_CT_NAME="${OPENCLAW_CT_NAME:-my-assistant}"
OPENCLAW2_CT_NAME="${OPENCLAW2_CT_NAME:-openclaw-2}"

# in-sandbox skill / workspace paths (fixed by the openshell image layout)
HSKILLS=/sandbox/.hermes/skills
HSKILLS_SUB=/sandbox/.hermes/skills/productivity
OCSKILLS=/sandbox/.openclaw/workspace/skills
OCWS=/sandbox/.openclaw/workspace

# ── container resolution (survives sandbox rebuilds: id changes each rebuild) ──
resolve_ct() {  # $1 = name fragment (hermes-demo | my-assistant | openclaw-2)
  docker ps --format '{{.Names}}' 2>/dev/null | grep -m1 "openshell-$1-" || true
}
CT_H="$(resolve_ct "$HERMES_CT_NAME")"
CT_O="$(resolve_ct "$OPENCLAW_CT_NAME")"

require_ct() {  # warn if a needed container is missing. $1=varname $2=human name
  local var="$1" name="$2"
  if [ -z "${!var}" ]; then
    echo "[lib] WARN: $name container not found (rebuilt? stopped?). docker ps | grep $name" >&2
    return 1
  fi
  return 0
}

# ── shared sub-libraries ──────────────────────────────────────────────────────
. "$LIB_DIR/scenarios.sh"
. "$LIB_DIR/routing.sh"
