#!/usr/bin/env bash
# common.sh — shared runtime config + helpers for all nemofleet scripts.
#
# Source it via the standard 3-line header (resolves repo root by the
# .nemofleet-root marker, so scripts work from any subfolder and on any host):
#
#   __src="${BASH_SOURCE[0]:-$0}"; __dir="$(cd "$(dirname "$(readlink -f "$__src" 2>/dev/null || echo "$__src")")" && pwd)"
#   while [ "$__dir" != / ] && [ ! -e "$__dir/.nemofleet-root" ]; do __dir="$(dirname "$__dir")"; done
#   NEMOFLEET_ROOT="$__dir"; DIR="$NEMOFLEET_ROOT"; . "$NEMOFLEET_ROOT/lib/common.sh"
#
# Everything host-specific (paths, node bin, ports, container names) is centralised
# here and overridable via $NEMOFLEET_ROOT/.env — see .env.example.

# ── repo root (authoritative: derive from this file's own location) ───────────
NEMOFLEET_ROOT="${NEMOFLEET_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
DIR="$NEMOFLEET_ROOT"   # back-compat alias used throughout the scripts
export NEMOFLEET_ROOT DIR   # so child services (e.g. the dashboard) inherit the root

# ── load local overrides (untracked) ─────────────────────────────────────────
[ -f "$NEMOFLEET_ROOT/.env" ] && . "$NEMOFLEET_ROOT/.env"

# ── notify secrets (Telegram/SMTP/TEAMLEAD_EMAIL), kept outside the repo entirely ──
# Same idea as the EBG19P_CRED convention below: real credentials never sit inside
# the nemofleet checkout (even git-ignored), only under $HOME so a repo copy/backup/
# reclone never carries them. Sourced last, so it overrides blank .env defaults.
# See .env.example for the exact key names to put in this file.
NOTIFY_ENV="${NOTIFY_ENV:-$HOME/.config/nemoclaw/nemofleet-notify.env}"
[ -f "$NOTIFY_ENV" ] && . "$NOTIFY_ENV"

# ensure HOME is set (autostart / systemd / cron contexts may not export it)
[ -n "${HOME:-}" ] || HOME="$(getent passwd "$(id -u)" 2>/dev/null | cut -d: -f6)"
export HOME

# ── node / CLI on PATH (nemoclaw + openshell live in node's bin) ──────────────
# Resolve NEMOFLEET_NODE_BIN (explicit .env value, else newest nvm node) and put
# it on PATH. Exported so scripts that set an explicit PATH (e.g. cron) can still
# reference $NEMOFLEET_NODE_BIN instead of a hardcoded version.
if [ -z "${NEMOFLEET_NODE_BIN:-}" ] && [ -d "$HOME/.nvm/versions/node" ]; then
  NEMOFLEET_NODE_BIN="$(ls -d "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -1)"
fi
export NEMOFLEET_NODE_BIN
if [ -n "${NEMOFLEET_NODE_BIN:-}" ]; then
  case ":$PATH:" in *":$NEMOFLEET_NODE_BIN:"*) ;; *) PATH="$NEMOFLEET_NODE_BIN:$PATH";; esac
fi
export PATH

# ── canonical directories ─────────────────────────────────────────────────────
LIB_DIR="$NEMOFLEET_ROOT/lib"
SCRIPTS_DIR="$NEMOFLEET_ROOT/scripts"
TESTS_DIR="$NEMOFLEET_ROOT/tests"
SERVICES_DIR="$NEMOFLEET_ROOT/services"
BRIDGE_DIR="$NEMOFLEET_ROOT/services/bridge"
MAIL_DIR="$NEMOFLEET_ROOT/services/mail"
CONFIG_DIR="$NEMOFLEET_ROOT/config"
SKILLS_DIR="$NEMOFLEET_ROOT/skills"
EVAL_DIR="$NEMOFLEET_ROOT/eval"
DATA_DIR="$NEMOFLEET_ROOT/data"
BUS_DIR="$NEMOFLEET_ROOT/data/bus"
LOG_DIR="$NEMOFLEET_ROOT/data/logs"
# Secrets are co-located with the bridge service but git-ignored (regenerated by
# scripts/gen-dash-ca.sh, scripts/gen-dash-tls.sh, scripts/rotate-bridge-token.sh).
BRIDGE_TOKEN_FILE="$BRIDGE_DIR/.bridge-token"   # team-lead → worker delegation token
APPROVAL_KEY_FILE="$BRIDGE_DIR/.approval-key"   # HMAC signing key for worker-c high-risk actions (rollback/firmware-apply); shared with team-lead's approval_issue.py only — see wi_approval.py
NVD_API_KEY_FILE="$BRIDGE_DIR/.nvd-api-key"
mkdir -p "$BUS_DIR/inbox" "$BUS_DIR/outbox" "$LOG_DIR" 2>/dev/null || true

# ── ports / endpoints (override in .env) ─────────────────────────────────────
HERMES_API_PORT="${HERMES_API_PORT:-8642}"        # team-lead OpenAI-compatible API (host)
DASH_PORT="${DASH_PORT:-8899}"
BRIDGE_PORT="${BRIDGE_PORT:-9099}"                # in-worker IT-ops endpoint (lead delegates here)
GATEWAY_PORT="${NEMOCLAW_GATEWAY_PORT:-18080}"
WORKERA_UI_PORT="${WORKERA_UI_PORT:-18789}"       # worker-a control UI
WORKERB_UI_PORT="${WORKERB_UI_PORT:-18790}"       # worker-b control UI
HERMES_API="http://127.0.0.1:${HERMES_API_PORT}/v1"

# ── inference routing (local NVIDIA NIM by default; override in .env) ─────────
# All three nodes run the Hermes harness on local Nemotron 3 Super 120B. The live provider is set
# into each sandbox via `nemoclaw inference set` (installed product, not vendored here);
# these vars document + drive scripts and the switch runbook.
INFER_PROVIDER="${INFER_PROVIDER:-nim}"
INFER_MODEL="${INFER_MODEL:-nvidia/nemotron-3-super-120b-a12b}"
INFER_ENDPOINT="${INFER_ENDPOINT:-http://127.0.0.1:8000/v1}"   # local NIM OpenAI-compatible endpoint

# ── real backends (no mocks). Connection details live in .env / cred files. ──
# Exported so child processes (dashboard, IT-ops endpoint, mail sender) inherit them.
EBG19P_CRED="${EBG19P_CRED:-$HOME/.config/nemoclaw/ebg19p.cred}"   # real device: IP|USER|PASS, chmod 600
SMTP_HOST="${SMTP_HOST:-}"; SMTP_PORT="${SMTP_PORT:-587}"          # real SMTP relay (outbound notifications)
SMTP_USER="${SMTP_USER:-}"; SMTP_PASS="${SMTP_PASS:-}"
SMTP_FROM="${SMTP_FROM:-}"; SMTP_STARTTLS="${SMTP_STARTTLS:-1}"
TEAMLEAD_EMAIL="${TEAMLEAD_EMAIL:-}"                               # team-lead's mailbox (its email adapter polls this)
JIRA_URL="${JIRA_URL:-}"; JIRA_USER="${JIRA_USER:-}"              # real Jira (escalations)
JIRA_TOKEN="${JIRA_TOKEN:-}"; JIRA_PROJECT="${JIRA_PROJECT:-NETOPS}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"                           # personal chat id — never committed
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"                       # enables the deterministic safety-net Telegram (Bot API direct)
export EBG19P_CRED SMTP_HOST SMTP_PORT SMTP_USER SMTP_PASS SMTP_FROM SMTP_STARTTLS TEAMLEAD_EMAIL
export JIRA_URL JIRA_USER JIRA_TOKEN JIRA_PROJECT TELEGRAM_CHAT_ID TELEGRAM_BOT_TOKEN
export INFER_PROVIDER INFER_MODEL INFER_ENDPOINT

# ── sandbox container name fragments (3-node Hermes fleet; override in .env) ──
TEAMLEAD_CT_NAME="${TEAMLEAD_CT_NAME:-team-lead}"     # human-facing coordinator
WORKERA_CT_NAME="${WORKERA_CT_NAME:-worker-a}"        # ops worker: monitor/drift/cert
WORKERB_CT_NAME="${WORKERB_CT_NAME:-worker-b}"        # security worker: CVE/SBOM/SAST/syslog
WORKERC_CT_NAME="${WORKERC_CT_NAME:-worker-c}"        # governance worker: backup/firmware/rollback/review

# in-sandbox skill / workspace paths (all nodes run the Hermes harness now)
HSKILLS=/sandbox/.hermes/skills
HSKILLS_SUB=/sandbox/.hermes/skills/productivity
WSKILLS=/sandbox/.hermes/workspace/skills   # worker skills
WWS=/sandbox/.hermes/workspace              # worker workspace (IT-task staging)

# ── container resolution (survives sandbox rebuilds: id changes each rebuild) ──
resolve_ct() {  # $1 = name fragment (team-lead | worker-a | worker-b)
  docker ps --format '{{.Names}}' 2>/dev/null | grep -m1 "openshell-$1-" || true
}

# primary_ip — the host's primary LAN IPv4, interface-name-agnostic. Uses the source IP the kernel
# would pick for outbound traffic (default route), so it works whether the NIC is eth0 / enP7s7 /
# ens5 / wlan0 (hardcoding "eth0" broke TLS cert signing on a DGX Spark whose NIC is enP7s7).
# Falls back to the first global-scope non-docker/bridge address. Empty only if truly offline.
primary_ip() {
  local ip
  ip="$(ip -4 route get 1.1.1.1 2>/dev/null | sed -n 's/.* src \([0-9.][0-9.]*\).*/\1/p' | head -1)"
  [ -n "$ip" ] || ip="$(ip -4 -o addr show scope global up 2>/dev/null | awk '$2 !~ /^(docker|br-|veth)/ {print $4}' | cut -d/ -f1 | head -1)"
  printf '%s' "$ip"
}
CT_LEAD="$(resolve_ct "$TEAMLEAD_CT_NAME")"
CT_WA="$(resolve_ct "$WORKERA_CT_NAME")"
CT_WB="$(resolve_ct "$WORKERB_CT_NAME")"
CT_WC="$(resolve_ct "$WORKERC_CT_NAME")"

require_ct() {  # warn if a needed container is missing. $1=varname $2=human name
  local var="$1" name="$2"
  if [ -z "${!var}" ]; then
    echo "[lib] WARN: $name container not found (rebuilt? stopped?). docker ps | grep $name" >&2
    return 1
  fi
  return 0
}

# ── EBG19P device access (single source of truth: services/bridge/ebg19p.py) ──
# One login per call; emits a JSON object. Used by the ebg19p-*-sync.sh scripts so the
# login / asus_token handling is never re-implemented per script.
ebg_nvget() {  # $1=cred_file, $2..=nvram keys → JSON {key: value}
  python3 "$BRIDGE_DIR/ebg19p.py" "$1" nvget "${@:2}"
}
ebg_hooks() {  # $1=cred_file, $2..=appGet hooks → JSON {hook: raw}
  python3 "$BRIDGE_DIR/ebg19p.py" "$1" hooks "${@:2}"
}

# ── SkillOS 治理閘(docs/design/skill-curation.md)────────────────────────────
# skill_gate <SKILL.md path> [name] — 技能落地前送 worker-c POST /skill-review 審(品質閘+抗膨脹)。
# 回 0=approve、1=reject(綁定,呼叫端勿落地)。worker-c 未部署/不可達 → 0+提示
# (gate-if-available:自我進化不因治理節點缺席而停擺;部署 zone C 後閘自動生效)。
skill_gate() {
  local f="$1" name="${2:-}" tok payload resp
  [ -n "$CT_WC" ] || { echo "[skill-gate] worker-c 未部署 → 未審放行(部署 zone C 後自動生效)" >&2; return 0; }
  tok="$(cat "$BRIDGE_TOKEN_FILE" 2>/dev/null || true)"
  [ -n "$tok" ] || { echo "[skill-gate] 無 bridge token → 未審放行" >&2; return 0; }
  payload=$(python3 -c 'import json,sys; print(json.dumps({"op":"insert","text":open(sys.argv[1],encoding="utf-8").read()}))' "$f") || return 0
  resp=$(printf '%s' "$payload" | docker exec -i "$CT_WC" sh -c "curl -s -m10 -X POST -H 'X-Bridge-Token: $tok' -H 'Content-Type: application/json' -d @- http://127.0.0.1:9099/skill-review" 2>/dev/null || true)
  case "$resp" in
    *'"verdict": "approve"'*|*'"verdict":"approve"'*)
      echo "[skill-gate] ✓ worker-c approve${name:+($name)}"; return 0 ;;
    *'"verdict": "reject"'*|*'"verdict":"reject"'*)
      echo "[skill-gate] ✗ worker-c REJECT${name:+($name)} — 不落地。required_fixes:" >&2
      printf '%s' "$resp" | python3 -c 'import sys,json
try:
    for x in json.load(sys.stdin).get("required_fixes", []): print("  -", x, file=sys.stderr)
except Exception: pass' >&2 || true
      return 1 ;;
    *) echo "[skill-gate] worker-c 未回應 → 未審放行" >&2; return 0 ;;
  esac
}

# ── shared sub-libraries ──────────────────────────────────────────────────────
. "$LIB_DIR/routing.sh"
