#!/usr/bin/env bash
# --- nemofleet: locate repo root + load shared library ---
__src="${BASH_SOURCE[0]:-$0}"; __dir="$(cd "$(dirname "$(readlink -f "$__src" 2>/dev/null || echo "$__src")")" && pwd)"
while [ "$__dir" != / ] && [ ! -e "$__dir/.nemofleet-root" ]; do __dir="$(dirname "$__dir")"; done
NEMOFLEET_ROOT="$__dir"; DIR="$NEMOFLEET_ROOT"; . "$NEMOFLEET_ROOT/lib/common.sh"
# import-fleet.sh — restore a fleet exported by export-fleet.sh onto THIS host.
#   Layer 3 (prereqs) — checked, not created: NemoClaw/OpenShell installed + the 4 sandboxes already
#     exist. If a sandbox is missing this errors out (create it via provisioning first).
#   Layer 1 (state)   — restored: secrets, the tamper-evident audit chain + key, the governance
#     ledger seen-set, device cred, host runtime data, and each worker sandbox's WD (docker cp'd in).
#   Layer 2 (derived) — re-generated by `make boot` at the end (IPs / tokens / policies / forwards).
#
# Usage: bash scripts/import-fleet.sh <bundle.tar.gz|.gpg> [--yes] [--dry-run] [--no-boot]
set -uo pipefail
BUNDLE=""; ASSUME_YES=0; DRY=0; DO_BOOT=1
while [ $# -gt 0 ]; do
  case "$1" in
    --yes) ASSUME_YES=1; shift ;;
    --dry-run) DRY=1; shift ;;
    --no-boot) DO_BOOT=0; shift ;;
    -h|--help) sed -n '6,15p' "$0"; exit 0 ;;
    -*) echo "unknown arg: $1" >&2; exit 2 ;;
    *) BUNDLE="$1"; shift ;;
  esac
done
[ -n "$BUNDLE" ] && [ -f "$BUNDLE" ] || { echo "用法: bash scripts/import-fleet.sh <bundle.tar.gz> [--yes] [--dry-run] [--no-boot]" >&2; exit 2; }
WD_IN="/sandbox/.hermes/workspace/it-task"; NC_CFG="$HOME/.config/nemoclaw"
ok(){ printf '  \033[32m✓\033[0m %s\n' "$1"; }
bad(){ printf '  \033[31m✗\033[0m %s\n' "$1"; }
skip(){ printf '  \033[33m·\033[0m %s\n' "$1"; }
act(){ [ "$DRY" = 1 ] && printf '  \033[36m→ (dry-run)\033[0m %s\n' "$1" || printf '  \033[32m✓\033[0m %s\n' "$1"; }

STAGE="$(mktemp -d)"; trap 'rm -rf "$STAGE"' EXIT
echo "== nemofleet import $(date -u '+%Y%m%d-%H%M%SZ') =="

# ── unpack (gpg-decrypt if needed) ─────────────────────────────────────────────────────────────
SRC="$BUNDLE"
case "$BUNDLE" in
  *.gpg) command -v gpg >/dev/null 2>&1 || { bad "bundle 是 gpg 加密的,但找不到 gpg"; exit 1; }
         gpg -d -o "$STAGE/bundle.tar.gz" "$BUNDLE" 2>/dev/null || { bad "gpg 解密失敗"; exit 1; }
         SRC="$STAGE/bundle.tar.gz"; ok "gpg 解密" ;;
esac
tar xzf "$SRC" -C "$STAGE" 2>/dev/null || { bad "解壓失敗(不是有效的 export bundle?)"; exit 1; }
ROOT="$(find "$STAGE" -maxdepth 1 -type d -name 'nemofleet-export-*' | head -1)"
[ -n "$ROOT" ] && [ -f "$ROOT/MANIFEST.json" ] || { bad "bundle 內找不到 MANIFEST.json —— 不是 export-fleet.sh 產的包"; exit 1; }
MANI_COMMIT="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1])).get("git_commit","?"))' "$ROOT/MANIFEST.json" 2>/dev/null || echo '?')"
ok "bundle 已解開(來源 git $MANI_COMMIT)"

# ── Layer 3 preflight ──────────────────────────────────────────────────────────────────────────
echo "-- Layer 3 前置檢查 --"
FATAL=0
for bin in docker; do command -v "$bin" >/dev/null 2>&1 && ok "$bin 在" || { bad "$bin 不在"; FATAL=1; }; done
command -v nemoclaw >/dev/null 2>&1 && ok "nemoclaw 在" || { bad "nemoclaw CLI 不在(見 provisioning/install-prereqs.md)"; FATAL=1; }
command -v openshell >/dev/null 2>&1 && ok "openshell 在" || skip "openshell CLI 不在(policy 重生會略過)"
for frag in "$TEAMLEAD_CT_NAME" "$WORKERA_CT_NAME" "$WORKERB_CT_NAME" "$WORKERC_CT_NAME"; do
  docker ps -a --format '{{.Names}}' 2>/dev/null | grep -q "openshell-$frag-" && ok "sandbox $frag 已存在" || { bad "sandbox $frag 不存在 —— 請先用 provisioning/onboard 建好 4 個沙箱再 restore"; FATAL=1; }
done
[ "$FATAL" = 1 ] && { echo; bad "前置未就緒,中止。補齊上面標 ✗ 的項目後再跑一次。"; exit 1; }
if [ "$MANI_COMMIT" != "?" ] && [ "$MANI_COMMIT" != "$(git -C "$NEMOFLEET_ROOT" rev-parse HEAD 2>/dev/null)" ]; then
  skip "注意:本 repo HEAD 與 bundle 的 git_commit 不同($MANI_COMMIT)。建議 checkout 到同一 commit 再 restore,避免碼/資料版本不一致。"
fi

# ── confirm (destructive: overwrites this host's secrets + sandbox data) ────────────────────────
if [ "$DRY" = 0 ] && [ "$ASSUME_YES" = 0 ]; then
  printf '  \033[33m⚠ 這會覆蓋本機的 secrets、稽核帳本、與各沙箱的 WD 資料。確定? [y/N] \033[0m'
  read -r ans; case "$ans" in y|Y|yes) ;; *) echo "  已取消。"; exit 0;; esac
fi

# ── Layer 1 restore: host-side ─────────────────────────────────────────────────────────────────
echo "-- Layer 1 還原(secrets + host 資料)--"
rst_dir(){ # $1=src-in-bundle $2=dest-dir  (copy contents if the bundle dir exists)
  [ -d "$1" ] || return 0
  if [ "$DRY" = 1 ]; then act "restore $2/ ← .../$(basename "$1")"; return 0; fi
  mkdir -p "$2"; cp -a "$1"/. "$2"/ 2>/dev/null && ok "restore → $2" || bad "restore 失敗 → $2"
}
rst_file(){ # $1=src-file $2=dest-dir-or-file
  [ -f "$1" ] || return 0
  if [ "$DRY" = 1 ]; then act "restore $2 ← .../$(basename "$1")"; return 0; fi
  cp -a "$1" "$2" && ok "restore → $2" || bad "restore 失敗 → $2"
}
rst_dir  "$ROOT/bridge-secrets"          "$BRIDGE_DIR"
rst_dir  "$ROOT/nemoclaw-config"         "$NC_CFG"
rst_file "$ROOT/env/.env"                "$NEMOFLEET_ROOT/.env"
rst_dir  "$ROOT/host-data/data"          "$DATA_DIR"
rst_dir  "$ROOT/host-data/eval/ledgers"  "$EVAL_DIR/ledgers"
rst_file "$ROOT/host-data/eval/lessons.json"       "$EVAL_DIR/"
rst_file "$ROOT/host-data/skills/skill-stats.json" "$SKILLS_DIR/"
# lock down secret perms
if [ "$DRY" = 0 ]; then
  for f in "$BRIDGE_DIR"/.bridge-token "$BRIDGE_DIR"/.approval-key "$BRIDGE_DIR"/.nvd-api-key "$BRIDGE_DIR"/dash-*-key.pem "$BRIDGE_DIR"/dash-key.pem "$NC_CFG"/admin-audit.hmac-key "$NC_CFG"/ebg19p.cred; do
    [ -f "$f" ] && chmod 600 "$f" 2>/dev/null
  done
  ok "secret 檔權限已設 600"
fi

# ── Layer 1 restore: each sandbox WD ───────────────────────────────────────────────────────────
echo "-- Layer 1 還原(沙箱 WD)--"
for frag in "$WORKERA_CT_NAME" "$WORKERB_CT_NAME" "$WORKERC_CT_NAME"; do
  src="$ROOT/sandboxes/$frag"
  [ -d "$src" ] && [ -n "$(ls -A "$src" 2>/dev/null)" ] || { skip "sandbox $frag(bundle 內無此台資料)"; continue; }
  ct="$(docker ps --format '{{.Names}}' 2>/dev/null | grep -m1 "openshell-$frag-" || true)"
  [ -n "$ct" ] || { bad "sandbox $frag 容器沒在跑,略過(啟動後可重跑 import)"; continue; }
  if [ "$DRY" = 1 ]; then act "docker cp → $frag:$WD_IN/ ($(find "$src" -type f|wc -l|tr -d ' ') files)"; continue; fi
  docker exec -u 0 "$ct" sh -c "mkdir -p $WD_IN" >/dev/null 2>&1
  if docker cp "$src/." "$ct:$WD_IN/" >/dev/null 2>&1; then
    docker exec -u 0 "$ct" sh -c "chown -R 998:998 $WD_IN" >/dev/null 2>&1
    ok "restore → $frag:$WD_IN"
  else bad "docker cp 失敗 → $frag"; fi
done

# ── Layer 2: re-derive IPs / tokens / policies + restart ───────────────────────────────────────
echo "-- Layer 2 重生(make boot)--"
if [ "$DRY" = 1 ]; then act "make boot(重簽憑證對齊本機 IP、注入還原的 token、重部署 worker-itops 並載入還原的 WD、重啟 dashboard/巡邏)"
elif [ "$DO_BOOT" = 1 ]; then
  bash "$NEMOFLEET_ROOT/scripts/boot-stack.sh" && ok "make boot 完成" || bad "boot 非零退出(看上面輸出)"
else skip "--no-boot:跳過 make boot(記得手動跑一次讓 Layer 2 生效)"; fi

echo
[ "$DRY" = 1 ] && echo "== dry-run 結束(未改動任何東西)==" || echo "== import 完成。開 https://<本機IP>:8899 驗證;跑 make health 檢查。 =="
